name: rotation_stage
description: A four-sided stage for representing 3D objects with four widgets
version: 0.2.0


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lintervention: ^0.1.1
  
  mocktail: ^1.0.3
