name: body_part_selector
description: A beautiful selector for different body parts
version: 0.3.1
homepage: https://www.whynotmake.it
repository: https://github.com/timcreatedit/body_part_selector

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_svg: ">=2.2.1" # https://github.com/dnfield/flutter_svg/issues/969
  freezed_annotation: ">=2.4.0 <3.0.0" 
  rotation_stage: ^0.3.0
  touchable: ^1.0.2
  meta: ^1.7.0
  path_drawing: ^1.0.1
  vector_math: ^2.1.2

  xml: ^6.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ">=2.4.0 <3.0.0"
  json_serializable: ">=6.8.0 <7.0.0"
  lintervention: ^0.1.1
  melos: ^6.0.0
  mocktail: ^1.0.3

flutter:
  assets:
    - packages/body_part_selector/m_front.svg
    - packages/body_part_selector/m_left.svg
    - packages/body_part_selector/m_back.svg
    - packages/body_part_selector/m_right.svg
    - packages/body_part_selector/assets/refresh-svgrepo-com.svg
